### PR TITLE
Fix audiobook progress not caching when app is offline

### LINKED ISSUE #319: Offline use play progress not persisting
Version 1.7.13

I have downloaded a few books I do not have remote access to my server. When I exit out of the app and relaunch after a listening session my book progress will be reverted to a previous timestamp. Just enabled local server to see if that fixes the issue, will report back

### PR DESCRIPTION
**Pull request by lucdsouza**
Fix #319. In `PlaybackSynchronizationService.runSync()`, it always hits this block when app is running offline:

```kotlin
if (playbackSession == null || playbackSession?.itemId != currentItem?.id || currentIndex != currentChapterIndex) {
    openPlaybackSession(overallProgress)
    currentChapterIndex = currentIndex
}
```

`openPlaybackSession()` fails silently, skipping `playbackSession.requestSync()` and cached progress updates.

I added a `localCacheRepository` call to ensure local progress updates regardless of online/offline status. Online sync is unchanged.

### CODE REVIEW

File: app/src/main/kotlin/org/grakovne/lissen/playback/service/PlaybackSynchronizationService.kt [hunk 1]
```diff
@@ -91,9 +93,20 @@ class PlaybackSynchronizationService
...
       val elapsedMs = exoPlayer.currentPosition
       val overallProgress = getProgress(elapsedMs) ?: return
+      val bookId = currentItem?.id ?: return
 
       Timber.d("Trying to sync $overallProgress for ${currentItem?.id}")
 
+      // Save locally first always.
+      serviceScope.launch(Dispatchers.IO) {
+        localCacheRepository
+          .syncProgress(bookId, overallProgress)
```
Comment (GrakovNe) [inline app/src/main/kotlin/org/grakovne/lissen/playback/service/PlaybackSynchronizationService.kt]: we already have 

```
    suspend fun syncProgress(
      sessionId: String,
      itemId: String,
      progress: PlaybackProgress,
    ): OperationResult<Unit> {
      Timber.d("Syncing Progress for $itemId. $progress")

      localCacheRepository.syncProgress(itemId, progress)

      val channelSyncResult =
        providePreferredChannel()
          .syncProgress(sessionId, progress)

      return when (preferences.isForceCache()) {
        true -> OperationResult.Success(Unit)
        false -> channelSyncResult
      }
    }
```

so, local sync is works on the other abstraction level
